/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ProduceTraceability {
  export type EventLogStruct = {
    action: string;
    fromId: string;
    toId: string;
    timestamp: BigNumberish;
  };

  export type EventLogStructOutput = [
    action: string,
    fromId: string,
    toId: string,
    timestamp: bigint
  ] & { action: string; fromId: string; toId: string; timestamp: bigint };
}

export interface ProduceTraceabilityInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addQualityCheck"
      | "createBatch"
      | "getBatch"
      | "getQualityCheck"
      | "owner"
      | "renounceOwnership"
      | "splitBatch"
      | "transferBatch"
      | "transferOwnership"
      | "updateQualityProof"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;

  encodeFunctionData(
    functionFragment: "addQualityCheck",
    values: [string, string[], string[], string[], string]
  ): string;
  encodeFunctionData(
    functionFragment: "createBatch",
    values: [string, BigNumberish, string, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getBatch", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getQualityCheck",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "splitBatch",
    values: [string, string, BigNumberish, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferBatch",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateQualityProof",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "addQualityCheck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBatch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getQualityCheck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "splitBatch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateQualityProof",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProduceTraceability extends BaseContract {
  connect(runner?: ContractRunner | null): ProduceTraceability;
  waitForDeployment(): Promise<this>;

  interface: ProduceTraceabilityInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addQualityCheck: TypedContractMethod<
    [
      batchId: string,
      pesticides: string[],
      fertilizers: string[],
      photos: string[],
      certHash: string
    ],
    [void],
    "nonpayable"
  >;

  createBatch: TypedContractMethod<
    [
      batchId: string,
      quantity: BigNumberish,
      farmerId: string,
      dataHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getBatch: TypedContractMethod<
    [id: string],
    [
      [
        string,
        string,
        bigint,
        string,
        string,
        bigint,
        ProduceTraceability.EventLogStructOutput[]
      ]
    ],
    "view"
  >;

  getQualityCheck: TypedContractMethod<
    [id: string],
    [
      [string[], string[], string[], string, bigint] & {
        pesticides: string[];
        fertilizers: string[];
        photos: string[];
        certificationHash: string;
        lastUpdated: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  splitBatch: TypedContractMethod<
    [
      parentId: string,
      childId: string,
      qty: BigNumberish,
      newHolder: string,
      dataHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  transferBatch: TypedContractMethod<
    [batchId: string, toId: string],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateQualityProof: TypedContractMethod<
    [batchId: string, photoHash: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addQualityCheck"
  ): TypedContractMethod<
    [
      batchId: string,
      pesticides: string[],
      fertilizers: string[],
      photos: string[],
      certHash: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createBatch"
  ): TypedContractMethod<
    [
      batchId: string,
      quantity: BigNumberish,
      farmerId: string,
      dataHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBatch"
  ): TypedContractMethod<
    [id: string],
    [
      [
        string,
        string,
        bigint,
        string,
        string,
        bigint,
        ProduceTraceability.EventLogStructOutput[]
      ]
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getQualityCheck"
  ): TypedContractMethod<
    [id: string],
    [
      [string[], string[], string[], string, bigint] & {
        pesticides: string[];
        fertilizers: string[];
        photos: string[];
        certificationHash: string;
        lastUpdated: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "splitBatch"
  ): TypedContractMethod<
    [
      parentId: string,
      childId: string,
      qty: BigNumberish,
      newHolder: string,
      dataHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferBatch"
  ): TypedContractMethod<[batchId: string, toId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateQualityProof"
  ): TypedContractMethod<
    [batchId: string, photoHash: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
